version: "3.7"
services:
    # image project
    app:
        build:
            args:
                user: joao
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - queue
        networks:
            - application-test

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - application-test

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - application-test

    # phpmyadmin
    adminphp:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - "mysql:db"
        ports:
            - "3382:80"
        networks:
            - application-test

    # queue
    queue:
        build:
            args:
                user: joao
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - application-test

    # redis
    redis:
        image: redis:latest
        networks:
            - application-test

networks:
    application-test:
        driver: bridge
